### ISSUE TITLE
Regarding the question about setting ensemble_alpha

### ISSUE THREAD

**Issue by Fantastic000** [HMHelloWorld/FedMR#2]
Dear Sir,

I am very interested in your work. When running the fedmr model, could you please advise on what the ensemble_alpha should be set to in order to achieve the experimental results presented in Table 1?

**Comment by HMHelloWorld** [comment]
What is ensemble_alpha?

**Comment by Fantastic000** [comment]
<img width="740" alt="WechatIMG35643" src="https://github.com/user-attachments/assets/083035f1-0f30-4064-897a-2df89cea6966">
The parameter is not set in `options.py`, and running the experiment will result in an error.

**Comment by HMHelloWorld** [comment]
This is a redundant parameter, just remove it.
